main_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - motor_front_left_shoulder
    - motor_front_left_leg
    - foot_motor_front_left
    - motor_front_right_shoulder
    - motor_front_right_leg
    - foot_motor_front_right
    - motor_rear_left_shoulder
    - motor_rear_left_leg
    - foot_motor_rear_left
    - motor_rear_right_shoulder
    - motor_rear_right_leg
    - foot_motor_rear_right
  gains:
    motor_front_left_shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_front_left_leg:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    foot_motor_front_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_front_right_shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_front_right_leg:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    foot_motor_front_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_rear_left_shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_rear_left_leg:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    foot_motor_rear_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_rear_right_shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor_rear_right_leg:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    foot_motor_rear_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1